# Docker Compose para Kevaluacion
version: '3.8'

services:
  kevaluacion:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: kevaluacion-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - app_logs:/app/logs
    networks:
      - kevaluacion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


volumes:
  app_logs:

networks:
  kevaluacion-network:
    driver: bridge
